### ISSUE TITLE
Wrong path for message bundles when URL based on Angular routing

### ISSUE THREAD

**Issue by joaquimvila** [systelab/systelab-translate#11]
**Description**
When loading an Angular application through an URL that contains items that
are part of the Angular routing, then the JSON files with the translated messages
are not found. According to the error message that appears on the browser console,
the path where "systelab-translate" tries to load the message bundles contains the
items that belong to the application routing (instead of being relative to the
server path).

**Steps to Reproduce**

1. Set up a server with an Angular application that uses routing (i.e. http://localhost:4200/)
2. Open a browser and navigate to an URL of the server set up on the previous step and containing items that are part of the Angular application routing (i.e. http://localhost:4200/section/subsection/) 
3. Show browser console: an error is displayed indicating that the message bundles are not found

- URL where "systelab-translate" looks for the message bundle:
 http://localhost:4200/section/subsection/i18n/language/MessagesBundle_en_US.json

- URL where the message bundle is:
 http://localhost:4200/i18n/language/MessagesBundle_en_US.json

**Comment by joaquimvila** [comment]
Pull request: #12

**Comment by alfonsserra** [comment]
Solved and released
